### ISSUE TITLE
CUDA NVCC compiler

### ISSUE THREAD

**Issue by zcxxlshirley** [luost26/DMRDenoise#2]
(DMRDenoise) cx@cx-System-Product-Name:~/NewDisk/xxl/DMRDenoise-master/ops/emd$ python setup.py install
running install
running bdist_egg
running egg_info
writing emd.egg-info/PKG-INFO
writing dependency_links to emd.egg-info/dependency_links.txt
writing top-level names to emd.egg-info/top_level.txt
reading manifest file 'emd.egg-info/SOURCES.txt'
writing manifest file 'emd.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'emd' extension
Emitting ninja build file /home/cx/NewDisk/xxl/DMRDenoise-master/ops/emd/build/temp.linux-x86_64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] /usr/bin/nvcc -I/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/site-packages/torch/include -I/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/site-packages/torch/include/TH -I/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/site-packages/torch/include/THC -I/home/cx/NewDisk/anaconda3/envs/DMRDenoise/include/python3.6m -c -c /home/cx/NewDisk/xxl/DMRDenoise-master/ops/emd/emd_cuda.cu -o /home/cx/NewDisk/xxl/DMRDenoise-master/ops/emd/build/temp.linux-x86_64-3.6/emd_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=emd -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
FAILED: /home/cx/NewDisk/xxl/DMRDenoise-master/ops/emd/build/temp.linux-x86_64-3.6/emd_cuda.o 
/usr/bin/nvcc -I/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/site-packages/torch/include -I/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/site-packages/torch/include/TH -I/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/site-packages/torch/include/THC -I/home/cx/NewDisk/anaconda3/envs/DMRDenoise/include/python3.6m -c -c /home/cx/NewDisk/xxl/DMRDenoise-master/ops/emd/emd_cuda.cu -o /home/cx/NewDisk/xxl/DMRDenoise-master/ops/emd/build/temp.linux-x86_64-3.6/emd_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=emd -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
nvcc fatal   : Path to libdevice library not specified
[2/2] c++ -MMD -MF /home/cx/NewDisk/xxl/DMRDenoise-master/ops/emd/build/temp.linux-x86_64-3.6/emd.o.d -pthread -B /home/cx/NewDisk/anaconda3/envs/DMRDenoise/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/site-packages/torch/include -I/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/site-packages/torch/include/TH -I/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/site-packages/torch/include/THC -I/home/cx/NewDisk/anaconda3/envs/DMRDenoise/include/python3.6m -c -c /home/cx/NewDisk/xxl/DMRDenoise-master/ops/emd/emd.cpp -o /home/cx/NewDisk/xxl/DMRDenoise-master/ops/emd/build/temp.linux-x86_64-3.6/emd.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=emd -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1423, in _run_ninja_build
    check=True)
  File "/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    'build_ext': BuildExtension
  File "/home/cx/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/cx/.local/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/cx/.local/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/cx/.local/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 174, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/cx/.local/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 160, in call_command
    self.run_command(cmdname)
  File "/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/cx/.local/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/cx/.local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 603, in build_extensions
    build_ext.build_extensions(self)
  File "/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/cx/.local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 437, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1163, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/cx/NewDisk/anaconda3/envs/DMRDenoise/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1436, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

How to solve this problem?

**Comment by luost26** [comment]
Have you installed the CUDA NVCC compiler correctly?
You may use the command `nvcc -V` to check your NVCC installation.

**Comment by lhthaha** [comment]
想请问一下为什么在编译emd时会出现以下报错：
(DMRDenoise) D:\DMRDenoise-master\ops\emd>python setup.py install
running install
running bdist_egg
running egg_info
creating emd.egg-info
writing emd.egg-info\PKG-INFO
writing dependency_links to emd.egg-info\dependency_links.txt
writing top-level names to emd.egg-info\top_level.txt
writing manifest file 'emd.egg-info\SOURCES.txt'
reading manifest file 'emd.egg-info\SOURCES.txt'
writing manifest file 'emd.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\site-packages\torch\utils\cpp_extension.py:238: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'emd' extension
creating D:\DMRDenoise-master\ops\emd\build
creating D:\DMRDenoise-master\ops\emd\build\temp.win-amd64-3.6
creating D:\DMRDenoise-master\ops\emd\build\temp.win-amd64-3.6\Release
Emitting ninja build file D:\DMRDenoise-master\ops\emd\build\temp.win-amd64-3.6\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -ID:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\site-packages\torch\include -ID:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\site-packages\torch\include\TH -ID:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -ID:\Users\Administrator\anaconda3\envs\DMRDenoise\include -ID:\Users\Administrator\anaconda3\envs\DMRDenoise\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" -c D:\DMRDenoise-master\ops\emd\emd.cpp /FoD:\DMRDenoise-master\ops\emd\build\temp.win-amd64-3.6\Release\emd.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=emd -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: D:/DMRDenoise-master/ops/emd/build/temp.win-amd64-3.6/Release/emd.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -ID:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\site-packages\torch\include -ID:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\site-packages\torch\include\TH -ID:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -ID:\Users\Administrator\anaconda3\envs\DMRDenoise\include -ID:\Users\Administrator\anaconda3\envs\DMRDenoise\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" -c D:\DMRDenoise-master\ops\emd\emd.cpp /FoD:\DMRDenoise-master\ops\emd\build\temp.win-amd64-3.6\Release\emd.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=emd -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
ninja: fatal: ReadFile: 句柄无效。

Traceback (most recent call last):
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\site-packages\torch\utils\cpp_extension.py", line 1423, in _run_ninja_build
    check=True)
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    'build_ext': BuildExtension
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\site-packages\setuptools\command\bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\site-packages\setuptools\command\bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\site-packages\torch\utils\cpp_extension.py", line 603, in build_extensions
    build_ext.build_extensions(self)
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\site-packages\torch\utils\cpp_extension.py", line 585, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\site-packages\torch\utils\cpp_extension.py", line 1163, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "D:\Users\Administrator\anaconda3\envs\DMRDenoise\lib\site-packages\torch\utils\cpp_extension.py", line 1436, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

我nvcc-V检查过cuda是正常安装的，版本是10.2

**Comment by luost26** [comment]
Hi all,

I have re-tested my code on a server with four 1080Ti's, four 2080Ti's and NVCC 10.1.105. There seems to be no problem on my machine.

I have googled the error message "nvcc fatal : Path to libdevice library not specified" but I found only limited information about the issue. Here is perhaps the most relevant one: [https://github.com/cudamat/cudamat/issues/40](https://github.com/cudamat/cudamat/issues/40) , which might be helpful for you. 

If the issue remains, please try clone this project: [https://github.com/Colin97/MSN-Point-Cloud-Completion](https://github.com/Colin97/MSN-Point-Cloud-Completion) and compile its EMD operator, because our EMD operator is taken from their project without any modification.
