### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by LitterWindwind** [luost26/DMRDenoise#8]
HI @luost26 
When I run train.py, it reports as follow
Traceback (most recent call last):
  File "train.py", line 56, in <module>
    main(hparams)
  File "train.py", line 21, in main
    module = PointCloudDenoising(hparams)
  File "/home/qiuf/DMRDenoise/models/denoise.py", line 23, in __init__
    self.hparams = hparams
  File "/home/qiuf/anaconda3/envs/DMRDenoise/lib/python3.6/site-packages/torch/nn/modules/module.py", line 826, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
 
I have no idea how to solve it? could you please provide some advice?

THANKS for your great work!

**Comment by luost26** [comment]
Hi,

What's the version of your `PyTorch Lightning` ?
The class `PointCloudDenoising` is a subclass of `pl.LightningModule`, so I guess there's something wrong with PL.

**Comment by LitterWindwind** [comment]
Solved!  Thanks~
